version: '3.3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=denis
      - POSTGRES_PASSWORD=9rommit
      - POSTGRES_DB=grimoire
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5434:5434
    command: -p 5434
  web:
    build: .
    environment:
      - PORT=9999
      - DATABASE_JNDI=jdbc:postgresql://postgres:5434/grimoire
      - DATABASE_USER=denis
      - DATABASE_PASSWORD=9rommit
      - LOCAL_STORAGE=~/GRIM
    ports:
      - "9999:9999"
    depends_on:
      - postgres      
volumes:
  data:
