version: '3.3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=denis
      - POSTGRES_PASSWORD=9rommit
      - POSTGRES_DB=grimoire
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  data:
