DROP TABLE IF EXISTS transition

CREATE TABLE IF NOT EXISTS transition (
  id BIGSERIAL NOT NULL,
  event VARCHAR(32) NULL DEFAULT NULL ,
  src_status VARCHAR(32) NULL DEFAULT NULL ,
  dest_status VARCHAR(32) NULL DEFAULT NULL ,
  handler_name VARCHAR(32) NULL DEFAULT NULL)

DROP TABLE IF EXISTS lang
  
CREATE TABLE IF NOT EXISTS lang (
  id VARCHAR(2) NULL DEFAULT NULL ,
  "name" VARCHAR(16) NULL DEFAULT NULL ,
  encodings VARCHAR(255) NULL DEFAULT NULL)

DROP TABLE IF EXISTS transition

CREATE  TABLE IF NOT EXISTS "user" (
  id BIGSERIAL NOT NULL,
  username VARCHAR(32) NOT NULL ,
  password VARCHAR(32) NOT NULL ,
  role VARCHAR NOT NULL DEFAULT "USER",
  enabled BOOLEAN NOT NULL DEFAULT TRUE ,
  native_lang_id VARCHAR(2))

DROP TABLE IF EXISTS text

CREATE  TABLE IF NOT EXISTS text (
  id BIGSERIAL NOT NULL,
  orig_path VARCHAR(128) NOT NULL ,
  utf8_path VARCHAR(128) NOT NULL ,
  encoding VARCHAR(32) NOT NULL)

DROP TABLE IF EXISTS dict

CREATE TABLE dict (
  id BIGSERIAL NOT NULL,
  "name" VARCHAR(128) NULL DEFAULT NULL ,
  orig_doc TEXT NULL DEFAULT NULL ,
  utf8_text  TEXT NULL DEFAULT NULL ,
  status VARCHAR(32) NULL DEFAULT NULL ,
  "encoding" VARCHAR(32) NULL DEFAULT NULL ,
  preview   TEXT NULL DEFAULT NULL ,
  lang_id VARCHAR(2) NOT NULL ,
  user_id BIGINT NOT NULL ,
  TEXT_id BIGINT NULL)

DROP TABLE IF EXISTS job

CREATE  TABLE IF NOT EXISTS job (
  id BIGSERIAL NOT NULL,
  progress INT NOT NULL DEFAULT 0 ,
  details VARCHAR(255) NULL DEFAULT NULL ,
  active   BOOLEAN  NOT NULL DEFAULT FALSE ,
  transition_id BIGINT NOT NULL ,
  dict_id BIGINT NOT NULL);

DROP TABLE IF EXISTS translator_provider

CREATE  TABLE IF NOT EXISTS translator_provider (
  id BIGINT NOT NULL ,
  title VARCHAR(32) NULL DEFAULT NULL ,
  host VARCHAR(64) NULL DEFAULT NULL ,
  req_pattern VARCHAR(255) NULL DEFAULT NULL ,
  res_pattern VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (id) )

DROP TABLE IF EXISTS word

CREATE  TABLE IF NOT EXISTS word (
  id BIGSERIAL NOT NULL,
  lang_id VARCHAR(2) NOT NULL ,
  value VARCHAR(32) NOT NULL)

DROP TABLE IF EXISTS translator

CREATE  TABLE IF NOT EXISTS translator (
  id BIGINT NOT NULL ,
  service_id BIGINT NOT NULL ,
  src_lang_id VARCHAR(2) NOT NULL ,
  dest_lang_id VARCHAR(2) NOT NULL)
  
DROP TABLE IF EXISTS translation

CREATE  TABLE IF NOT EXISTS translation (
  id BIGSERIAL NOT NULL,
  value VARCHAR(64) NULL DEFAULT NULL ,
  word_id BIGINT NOT NULL ,
  translator_id BIGINT,
  user_id BIGINT,
  pre_text VARCHAR(128) NULL DEFAULT NULL ,
  post_text  VARCHAR(128) NULL DEFAULT NULL)

DROP TABLE IF EXISTS dict_word

CREATE  TABLE IF NOT EXISTS dict_word (
  id BIGSERIAL NOT NULL,
  counter BIGINT NOT NULL,
  dict_id BIGINT NOT NULL,
  word_id BIGINT NOT NULL,
  translation VARCHAR, 
  translator VARCHAR,
  occurances TEXT)

DROP TABLE IF EXISTS user_lang

CREATE  TABLE IF NOT EXISTS user_lang (
  id BIGSERIAL NOT NULL,
  user_id BIGINT NOT NULL ,
  lang_id VARCHAR(2) NOT NULL)